# Generated by Django 2.1.4 on 2021-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('birth_year', models.DateField(max_length=20)),
                ('adress', models.CharField(max_length=60)),
            ],
        ),
    ]
